# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd src
        dotnet restore
    - name: generate docfx site
      run: |
        dotnet tool install -g docfx
        docfx init -y

        # override default config, toc, and index page
        cp .docfx/* .
        cp README.md index.md

        docfx docfx.json
        ls -alh _site
    - name: push site to gh-pages
      run: |
          git config --global user.name 'Miha Zidar'
          git config --global user.email 'm.zidar@sportradar.com'
          git checkout -B gh-pages
          mv _site .git/
          rm -rf *
          mv .git/_site/* .
          git add .
          git commit -am "Automated github page generation"
          git push origin gh-pages -f
